# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a1f62260fdf7f2dc2430c6a7b9a8d214a3683bfadec5febea5cb46d5eae204426ef29d4e2d852c2989cb3f09d84ddd4d38dc0ab9bcdfcf2e28716fddab999ab

test:
  secret_key_base: 53f9e2fa3c5cbac94fea6dec3754acc04864a189c2dbf733464213d6131ed9d41f0aa335754a130ebf3c1f5d7b4a26f47fe9490648fe750f04fe2ac33b872a35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
